### ISSUE TITLE
[Bug] Server crash because Shadowmap

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#10]
Description
=======
Hi!
I wanna to let you know the server crash by starting a server.

Screenshots
========
![grafik](https://user-images.githubusercontent.com/65916181/232250940-a737f6f0-dbc4-46ae-adfb-3aeecafafa6c.png)

**Comment by aquagoose** [comment]
This should now be fixed as shadow maps have been disabled + easel now has proper server support.

**Comment by MrScautHD** [comment]
nice work!
