### ISSUE TITLE
[Bug] Light color bugs wierd

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#12]
Description
=======
Hello!
By trying out the color system of the light i saw this wierd bug happen, the light just cuts of.

Screenshots
========
![grafik](https://user-images.githubusercontent.com/65916181/232251283-0851b207-22a9-49ff-a203-15587bdcc055.png)

**Comment by aquagoose** [comment]
this is to do with the shadow mapping which is currently experimental

**Comment by aquagoose** [comment]
shadow mapping has (again) been disabled so this issue should be fixed. please reopen if it is not.

shadow mapping will be fixed when i rewrite the renderer.

**Comment by MrScautHD** [comment]
ok, i let you know!
