### ISSUE TITLE
🧊[Feature] Add Option to set the SampleState already in the ImageContent [Priority: Low]

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#16]
Description
=======
Hello!
I would love if it possible to set the SampleState of Textures in the ImageContent
```cs
.Add(new ImageContent("logo/logo.png"), SamplerState.PointClamp)...
```

Priority: LOW

**Comment by aquagoose** [comment]
Sampler states have a similar issue to materials, although I could make it take a `SamplerStateDescription` instead.

**Comment by MrScautHD** [comment]
Would nice!

**Comment by MrScautHD** [comment]
oh you not wanna add this?
