### ISSUE TITLE
[Feature] Add Option to set the Material of a Model already in the ModelContent

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#17]
Description
=======

Hello!
I would love if it possible to set the Material of Models in the ModelContent
```cs
.Add(new ModelContent("entity/vehicle/cyber_car.glb", MaterialRegistry.CyberCar, false))...
```

**Comment by aquagoose** [comment]
this is not possible for a few reasons:
- Materials are a graphical resource, as such they allocate system resources, meaning they can't be used as content parameters.
- Even if I created some "Material Definition" (which the V2 renderer *is* going to implement), models contain multiple different materials in them and cannot easily just have one "global" material. While simple models do have a single global material, complex models usually have several.

**Comment by MrScautHD** [comment]
oh ok
