### ISSUE TITLE
[Feature] Add Graphic Settings

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#19]
Description
=======
**_I would love to see this Graphic options in Easel:_**

MSAA/FXAA Support (Off, X2-X32)
Render Distance (1%-100%)
Shadow (Off, Normal, High) (Maybe shadow amount too)
Motion Blur Strength (Off, Normal, High)
Reflection (Normal, High)
Output Monitor (monitor number)

**Comment by aquagoose** [comment]
Render distance as in... minecraft render distance? The one that affects how many chunks render? Easel does not handle any of that, and it is not designed to. I do have my own Easel extensions that do this however they are closed source for the use of SpaceBox only.

I don't think I'll be adding motion blur as it is a horrible effect.

The rest are already in the todo list, and as such I will be closing this.

**Comment by MrScautHD** [comment]
Motion blur can look cool if you use it right
