### ISSUE TITLE
Physics missing key methods

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#23]
Hi!
By moving to the new Physic lib you forgoten to add:
- [x] RayHit https://github.com/amerkoleci/JoltPhysicsSharp/commit/c86d27f8e508335fff2f398e0ab71ed87028f07e
- [ ]  LockX/Y/Z
- [ ]  Mass

[Edit]
- [x] The Gravity is set way to strong. (Should be fixed with: https://github.com/piegfx/Easel/issues/27)

I hope you can add it back :)

**Comment by MrScautHD** [comment]
Oh and i see the Gravity is wayyy to strong that should get fixed too :)

**Comment by aquagoose** [comment]
In what way is it too strong? It should be set to `(0, -9.81, 0)`, which, assuming your application uses 1 easel unit as 1m, should be accurate to reality.

**Comment by aquagoose** [comment]
You can also adjust the gravity as you wish in the `Physics`. I will add an option for `PhysicsInitializeSettings` in the `GameSettings`.

**Comment by MrScautHD** [comment]
> You can also adjust the gravity as you wish in the `Physics`. I will add an option for `PhysicsInitializeSettings` in the `GameSettings`.

ok because i tried it out, and my car was instand gone...

**Comment by aquagoose** [comment]
Could you upload a video of what is happening?

**Comment by MrScautHD** [comment]
Sure:
https://user-images.githubusercontent.com/65916181/235496819-a91f3118-32b7-4ff1-b481-8e4d89071655.mp4

**Comment by aquagoose** [comment]
Double check you're not applying forces/setting velocity or anything like that?

Can you check what gravity is? Should be `Simulation.PhysicsSystem.Gravity`.

**Comment by MrScautHD** [comment]
Yea i commend everything out:
![grafik](https://user-images.githubusercontent.com/65916181/235497259-fd6ab098-8e84-42a1-862e-9aea55c88486.png)

**Comment by MrScautHD** [comment]
![grafik](https://user-images.githubusercontent.com/65916181/235497585-f7f92d1e-464a-448e-b963-50d2e1aa8108.png)

**Comment by aquagoose** [comment]
Can you log the linear velocity of the car? What scale is it?

**Comment by MrScautHD** [comment]
![grafik](https://user-images.githubusercontent.com/65916181/235498023-a88213b9-e1ef-4bcd-9c7c-5f7d4eaf092a.png)

**Comment by MrScautHD** [comment]
It goes slowly higher its now by -196,02505

**Comment by MrScautHD** [comment]
> Can you log the linear velocity of the car? What scale is it?

what you mean with scale?
If you mean the Shape: new BoxShape(new Vector3(3));

**Comment by aquagoose** [comment]
The scale of the entity/model.

**Comment by MrScautHD** [comment]
> 

What? can you give me pls a example sry i do not understand.

**Comment by aquagoose** [comment]
as in `entity.Transform.Scale`, and your model scale (for example is it 1x1x1m, bigger, smaller, etc)

**Comment by MrScautHD** [comment]
> as in `entity.Transform.Scale`, and your model scale (for example is it 1x1x1m, bigger, smaller, etc)

its <1. 1. 1>

**Comment by MrScautHD** [comment]
RayHit added with https://github.com/amerkoleci/JoltPhysicsSharp/commit/c86d27f8e508335fff2f398e0ab71ed87028f07e

**Comment by MrScautHD** [comment]
The Gravity should be fixed with: https://github.com/piegfx/Easel/issues/27

**Comment by aquagoose** [comment]
Why have you replaced the title of all of these with a ladybird? I would appreciate it if you could please use labels for these issues so they are easier to sort.

**Comment by MrScautHD** [comment]
> Why have you replaced the title of all of these with a ladybird? I would appreciate it if you could please use labels for these issues so they are easier to sort.

I can not set Labels...

**Comment by aquagoose** [comment]
Oh, I thought you could. Nevermind then!

**Comment by MrScautHD** [comment]
I has a small bug founded:

 ApplyForce needs a value of `4000000` to move up!

```cs
this.Rigidbody.ApplyForce(new Vector3(0, 4000000, 0));
```

Should it not work like Gravity?
-10 is gravity so + 15 to make it move up 


PS: I use the FixedUpdate Method

**Comment by aquagoose** [comment]
> "Priority: High"

Any reason you have added this label?

**Comment by MrScautHD** [comment]
> > "Priority: High"
> 
> Any reason you have added this label?

I thought it would cool to add a Priority, but well i can remove it

**Comment by aquagoose** [comment]
If you think this changes the way I will be adding features you are wrong my friend.

**Comment by MrScautHD** [comment]
;)
