### ISSUE TITLE
[Bug] FPS are constant 60 if Fullscreen!

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#26]
Hi, we talked already about it!
By starting the game in fullscreen with 1920x1080, The game does have a fps constant on 60 FPS but if i try to start it with OpenGL everything works fine and i get 2500 Fps!

Code:
```cs
GameSettings settings = new GameSettings {
    Title = "Stellution (WIP)",
    Icon = new Bitmap("content/bitmaps/logo/logo.bmp"),
    AutoGenerateContentDirectory = null,
    TitleBarFlags = TitleBarFlags.ShowGraphicsApi,
    VSync = false,
    Border = WindowBorder.Resizable,
    Size = new Size<int>(1920, 1080),
    Fullscreen = true,
    //Api = GraphicsApi.OpenGL
};

using StellutionClient game = new StellutionClient(settings, new Earth());
game.Run();
```

https://github.com/piegfx/Easel/assets/65916181/56c910ae-922b-4c41-97ad-c536e9a1323b

**Comment by aquagoose** [comment]
Closing as this is not an issue specific to Easel.

**Comment by MrScautHD** [comment]
Huu, what then?
Oh well, Pie...

**Comment by MrScautHD** [comment]
Is it a pie or silk issue?
