### ISSUE TITLE
[Feature] Add option to disable font smoothing!

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#3]
Hey i added my font and there is no way to disable the smoothing of the text.

I would really like it if you could add a option for it.
![Unbeafnannt](https://user-images.githubusercontent.com/65916181/219968782-e71f44d6-e92a-4650-ab18-ee7aaf367980.png)

**Comment by aquagoose** [comment]
This will need to be added upstream to Pie's FreeType library.

**Comment by aquagoose** [comment]
In my testing, the font antialiasing is certainly nowhere near this bad. Even still, I added an option to disable font antialiasing with the latest commit https://github.com/piegfx/Easel/commit/e7c7a07e3ac59af09449450d7b13db3d64ac57f4. Hopefully this fixes your problem!

**Comment by MrScautHD** [comment]
Thx good work
