### ISSUE TITLE
Add support for headless instances

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#4]
Hey i tried todo a Server with this Framework and it is very hard to setup one.

I would like if you maybe can do a RunClient and a RunServer Method in the Game class (the server does not start the graphic things...)

**Comment by MrScautHD** [comment]
Or create a IsServer Variable in the GameSettings to check if it a Server then disable the client things...

**Comment by MrScautHD** [comment]
```cs
    protected override void Draw() {
        if (GameSettings.IsServer) {
            return;
        }
        
        base.Draw();
    }
    ```

**Comment by MrScautHD** [comment]
something like that ^^

**Comment by aquagoose** [comment]
I've added the beginnings of server support - It's not great but it's a start. I'll get to work with a proper headless mode shortly.

**Comment by MrScautHD** [comment]
> I've added the beginnings of server support - It's not great but it's a start. I'll get to work with a proper headless mode shortly.

nice!

**Comment by aquagoose** [comment]
This has now been implemented and should (mostly) be working properly,

**Comment by MrScautHD** [comment]
nice!
