### ISSUE TITLE
[Feature] FixedUpdate Method

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#5]
Hey it would really cool if you could setup a FixedUpdate Method that not slow down the Draw Method!

(We spooke already about it, but for your Todo list is it maybe better so write it here too)

**Comment by aquagoose** [comment]
FixedUpdate has been added too, its implementation is primitive but will be fixed when I update how the game loop works.

**Comment by MrScautHD** [comment]
nice good work!
