### ISSUE TITLE
[Feature] Content Parameters!

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#6]
Add to the `LoadContentItem`  a HashSet. (By default is it set to null because not every object does need a parameter)

```cs
public interface IContentTypeReader
{
    public object LoadContentItem<T>(string path, HashSet<T> = null);
}
```

Then you can use in like the model loader:
```cs
    public object LoadContentItem(string path, HashSet<ModelEnum> options)
    {
        return new Model(path, options.Contains(ModelEnum.flipUv));
    }

    public enum ModelEnum
    {
        flipUv
    }
```

And you able to call it with:
```cs
        HashSet<ModelEnum> options = new HashSet<ModelEnum>();
        options.Add(ModelEnum.flipUv);
        
        Model model = content.Load<Model>("path...", options);
```
        
        PS: By setting the parameter in a enum can nothing get broken

**Comment by aquagoose** [comment]
Sorry, this will not be added. The content manager API is designed the way it is for a reason.

**Comment by MrLiquid4k** [comment]
OMG! i need this
