### ISSUE TITLE
[FEATURE] CONTENT BUILDER

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#7]
Hey!

Could you pls make the `AddContent` Method in ContentManger Overwriteable, so i can add it more times...

Example:
```cs
    public void AddContent(ContentDefinition definition, bool overwrite = false)
    {
        if (_definitions.Count == 0)
            _defaultName = definition.Name;
        
        if (overwrite)
            _definitions.Remove(definition.Name)
        
        _definitions.Add(definition.Name, definition);
    }
```

And Make the `_types` public to the getter in ContentBuilder, so i can check what get already added and i not add it again (Override it)

**Comment by aquagoose** [comment]
I have already said no, this will not be implemented.

**Comment by MrScautHD** [comment]
> I have already said no, this will not be implemented.
not even that small feature??

**Comment by MrScautHD** [comment]
you not even need to make it to a overwrite method just make _definitions public

**Comment by aquagoose** [comment]
Because I have said no several times to you. This goes against the nature of the content builder and will therefore not be implemented.
