### ISSUE TITLE
Model rigging + animations 

### ISSUE THREAD

**Issue by MrScautHD** [piegfx/Easel#9]
Hey, i would like to see that you add the Rig (Bone) Support, That we can enjoy your Engine with cool Animations!
![grafik](https://github.com/piegfx/Easel/assets/65916181/7e809729-4c1a-4381-8801-6d9fc51c1e6e)

**Comment by MrScautHD** [comment]
Because you told me you don't know how to add bones with Assimp, here is a lib that added bones:
https://github.com/LiruJ/MonoGame-Skinned-Mesh-Importer/tree/master (MIT License)

**Comment by aquagoose** [comment]
I am quite capable of adding this myself.

**Comment by MrScautHD** [comment]
> 

yea sure, i just mean to take a look on it.

**Comment by aquagoose** [comment]
I am perfectly capable of looking into it myself.
